name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.0, 7.4]
        testbench: [7.0, 6.23]
        version: [prefer-stable, prefer-lowest]
        include:
          - version: prefer-stable
            meilisearch: latest
            meilicmd: meilisearch
          - version: prefer-lowest
            meilisearch: v0.28.0
            meilicmd: ./meilisearch
        exclude:
          - php: 7.4
            testbench: 7.0

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - T${{ matrix.testbench }} - ${{ matrix.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQLite 3
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer remove --dev friendsofphp/php-cs-fixer --no-update --no-interaction
          composer require "orchestra/testbench:^${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.version }} --prefer-dist --no-interaction

      - name: Meilisearch setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ matrix.meilisearch }} ${{ matrix.meilicmd }} --master-key=masterKey --no-analytics

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Execute tests
        run: vendor/bin/phpunit
